apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  MYSQL_HOST: db-srv
  MYSQL_USER: root
  MYSQL_DATABASE: patients
  NODE_ENV: development
  PORT: "5000"
  EMAIL_SERVICE_BASE_URL: http://email-srv:3001/api
  LOGGER_FILE: "backend.log"
  LOGGER_ERROR_FILE: "backend-error.log"
  LOGGER_LEVEL: "info"
